# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    # ✅ Use official Gradle action (works with or without gradlew)
    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '8.9' # Change if needed

    - name: Grant execute permission for gradlew (if exists)
      run: |
        if [ -f gradlew ]; then
          chmod +x gradlew
        fi

    - name: Build and run tests
      run: |
        if [ -f gradlew ]; then
          ./gradlew build
        else
          gradle build
        fi

    - name: Upload build reports (optional)
      uses: actions/upload-artifact@v4
      with:
        name: build-reports
        path: build/reports

