name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # If your project has a gradlew script, use it:
      - name: Build with Gradle Wrapper
        run: ./gradlew build --stacktrace --info

      # If you want to run tests separately, uncomment:
      # - name: Run Tests
      #   run: ./gradlew test --stacktrace --info

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Use gradlew if available, otherwise setup Gradle
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
